version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Run tests for day 1
          command: go test reportrepair
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
