(load "binarydiagnostic/main.lisp")
(load "dive/main.lisp")
(load "giantsquid/main.lisp")
(load "hydrothermalventure/main.lisp")
(load "sonarsweep/main.lisp")
(defpackage :main
  (:use :cl)
  (:import-from binarydiagnostic :run-binarydiagnostic)
  (:import-from dive :run-dive)
  (:import-from giantsquid :run-giantsquid)
  (:import-from hydrothermalventure :run-hydrothermalventure)
  (:import-from sonarsweep :run-sonar-sweep)
)
(in-package :main)

(defun newline ()
  (format t "~C" #\linefeed)
)

(run-sonar-sweep)
(newline)
(run-dive)
(newline)
(run-binarydiagnostic)
(newline)
(run-giantsquid)
(newline)
(run-hydrothermalventure)
(newline)
